name: "maintenance"
permissions: read-all
on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight
jobs:
  stale:
    name: "close stale issues and pull requests"
    runs-on: ubuntu-latest
    permissions:
      issues: write # for actions/stale to close stale issues
      pull-requests: write # for actions/stale to close stale PRs
    steps:
      # Harden workflow runner
      - name: Harden workflow runner (audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Tag stale issues and PRs
        uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          # On the 'debug' mode the action will not perform any operation.
          # Add the secret ACTIONS_STEP_DEBUG with a value of 'true' in the repository.
          debug-only: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 45
          days-before-close: 5
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "help wanted,awaiting approval,work in progress"
          exempt-pr-labels: "help wanted,awaiting approval,work in progress"
          stale-issue-message: "This issue has been marked as **stale** because it has not registered any activity during the last 45 days. If the **stale** label is not removed or no activity is registered, this will be automatically closed in 5 days."
          close-issue-message: "This issue has been closed automatically after not registering any activity for 50 consecutive days."
          stale-pr-message: "This pull request has been marked as **stale** because it has not registered any activity during the last 45 days. If the **stale** label is not removed or no activity is registered, this will be automatically closed in 5 days."
          close-pr-message: "This pull request has been closed automatically after not registering any activity for 50 consecutive days."
